"""Materialize a readable service/data/control *projection* of Prolog's static BT graph.

Inputs: outputs/service_graph.json generated by `python -m sg_pipeline.convert`
and the explicit design access contracts sg_pipeline/access_map.json.
This does not claim a feasible per-request execution trace or deployment DAG.
"""
from __future__ import annotations
import argparse
import json
import os
from pathlib import Path

SERVICE_ID = 'dialogue-service-v1'
BB_KEYS = ('normalized_input', 'topic', 'intent', 'slots')


def project(graph: dict, tree: dict, access: dict) -> dict:
    """Preserve Prolog-derived service nodes/dependency edges and add a readable view."""
    node_map = tree['nodes']
    source_nodes = {n['id']: n for n in graph['nodes']}
    services = {n['id']: dict(n) for n in graph['service_nodes']}
    if not services or set(services) - set(source_nodes):
        raise ValueError('Invalid Prolog service nodes')
    # Action IDs and type information come from Prolog output; do not guess type
    # from display title. Keep the service graph separate from the BT graph.
    rows = []
    for nodeid, n in services.items():
        if nodeid not in node_map:
            raise ValueError(f'Unknown service ID {nodeid}')
        rows.append({'id': nodeid, 'name': n['label'],
                     'source_node_id': nodeid, 'source_name': node_map[nodeid]['name']})
    node_ids = set(services)
    access_rows = []
    for service in rows:
        contract = access.get(service['source_name'], {})
        for direction in ('reads', 'writes'):
            for key in contract.get(direction, []):
                if key not in BB_KEYS:
                    raise ValueError(f'Unknown blackboard key {key!r}')
                access_rows.append({'service': service['id'], 'key': key,
                                    'direction': direction})
    access_rows = sorted(access_rows, key=lambda x: (x['service'], x['key'], x['direction']))
    # These edges are Prolog's static *candidate* edges; retain that qualification.
    possible = sorted({(e['source'], e['target'], e['key'])
                       for e in graph['service_data_edges']
                       if e['source'] in node_ids and e['target'] in node_ids},
                      key=lambda x: (x[0], x[1], x[2]))
    potential = [{'source': src, 'target': dst, 'key': key}
                 for src, dst, key in possible]

    # Hand-audited *architectural projection* of the fixed dialogue manager.
    # Gateways are NOT deployable services or a reimplementation of BT semantics.
    by_name = {n['source_name']: n['id'] for n in rows}
    required = ('ActionSpeechToText', 'ActionNormalizeInput',
                'ActionNaiveBayesTopicClassifier', 'Detect Intern',
                'Ask clarifying question', 'ActionQueryMusic', 'ActionQueryArt',
                'ActionBuildAnswerContext', 'ActionSharedLLM')
    if not all(x in by_name for x in required):
        raise ValueError('Tree differs from expected music/art dialogue design')
    stt, normal, topic, intent, ask, music, art, context, llm = (by_name[x] for x in required)
    gates = [
        {'id': 'gate:input', 'name': 'Input modality (Voice / Text)', 'rule': 'New input; voice or text'},
        {'id': 'gate:slots', 'name': 'Slot filling controller', 'rule': 'Missing mandatory slots? Loop until complete'},
        {'id': 'gate:topic', 'name': 'Topic router', 'rule': 'Music versus Art; exclusive branch'},
    ]
    # CONDITIONAL_FLOW is a presentation-level projection of the BT logic;
    # it is distinct from Prolog's static candidate data dependencies.
    flow = [
        ('gate:input', stt, 'voice'), ('gate:input', normal, 'text'),
        (stt, normal, 'voice_transcribed'),
        (normal, topic, 'success'), (topic, intent, 'success'),
        (intent, 'gate:slots', 'success'),
        ('gate:slots', ask, 'slots_missing'), (ask, 'gate:slots', 'repeat_after_reply'),
        ('gate:slots', 'gate:topic', 'slots_complete'),
        ('gate:topic', music, 'topic_music'), ('gate:topic', art, 'topic_art'),
        (music, context, 'music_result'), (art, context, 'art_result'),
        (context, llm, 'ready_to_verbalize'),
    ]
    return {'graph_id': SERVICE_ID, 'source_graph_id': 'dialogue-tree-v1',
            'mode': 'static_architectural_projection',
            'notice': ('Service/data edges are potential from Prolog and explicit access contracts. '
                       'Conditional flow is a documented design projection, not a runtime trace.'),
            'services': rows, 'blackboard_keys': list(BB_KEYS), 'access': access_rows,
            'potential_service_data': potential, 'gateways': gates,
            'conditional_flow': [{'source': s, 'target': t, 'guard': guard}
                                 for s, t, guard in flow]}


def upload(view: dict, uri: str | None = None, user: str | None = None,
           password: str | None = None) -> dict:
    from neo4j import GraphDatabase
    uri = uri or os.environ.get('NEO4J_URI')
    user = user or os.environ.get('NEO4J_USER', 'neo4j')
    password = password or os.environ.get('NEO4J_PASSWORD')
    if not uri or not password:
        raise ValueError('Set NEO4J_URI and NEO4J_PASSWORD in the terminal')
    gid = view['graph_id']
    with GraphDatabase.driver(uri, auth=(user, password)) as driver:
        driver.verify_connectivity()
        def write(tx):
            # Only nodes from THIS separate SG are replaced, never existing BTNode data.
            tx.run('MATCH (n:SGService {graph_id:$gid}) DETACH DELETE n', gid=gid).consume()
            tx.run('MATCH (n:SGBlackboardKey {graph_id:$gid}) DETACH DELETE n', gid=gid).consume()
            tx.run('MATCH (n:SGGateway {graph_id:$gid}) DETACH DELETE n', gid=gid).consume()
            tx.run('''UNWIND $rows AS item CREATE (:SGService {graph_id:$gid, id:item.id,
                     name:item.name, source_node_id:item.source_node_id,
                     source_name:item.source_name})''', rows=view['services'], gid=gid).consume()
            tx.run('''UNWIND $rows AS key CREATE (:SGBlackboardKey {graph_id:$gid,
                     id:key, name:key})''', rows=view['blackboard_keys'], gid=gid).consume()
            tx.run('''UNWIND $rows AS item CREATE (:SGGateway {graph_id:$gid, id:item.id,
                     name:item.name, rule:item.rule})''', rows=view['gateways'], gid=gid).consume()
            tx.run('''UNWIND $rows AS item
                     MATCH (a:SGService {graph_id:$gid, id:item.service})
                     MATCH (b:SGBlackboardKey {graph_id:$gid, id:item.key})
                     FOREACH (_ IN CASE WHEN item.direction='reads' THEN [1] ELSE [] END |
                       CREATE (a)-[:READS {contract:'proposed'}]->(b))
                     FOREACH (_ IN CASE WHEN item.direction='writes' THEN [1] ELSE [] END |
                       CREATE (a)-[:WRITES {contract:'proposed'}]->(b))''',
                   rows=view['access'], gid=gid).consume()
            tx.run('''UNWIND $rows AS item
                     MATCH (a:SGService {graph_id:$gid, id:item.source})
                     MATCH (b:SGService {graph_id:$gid, id:item.target})
                     CREATE (a)-[:POSSIBLE_DATAFLOW {key:item.key, certainty:'potential'}]->(b)''',
                   rows=view['potential_service_data'], gid=gid).consume()
            tx.run('''UNWIND $rows AS item
                     MATCH (a {graph_id:$gid, id:item.source})
                     WHERE a:SGService OR a:SGGateway
                     MATCH (b {graph_id:$gid, id:item.target})
                     WHERE b:SGService OR b:SGGateway
                     CREATE (a)-[:CONDITIONAL_FLOW {guard:item.guard,
                                semantics:'design_projection'}]->(b)''',
                   rows=view['conditional_flow'], gid=gid).consume()
        with driver.session() as session:
            session.execute_write(write)
    return {'graph_id': gid, 'services': len(view['services']),
            'blackboard_keys': len(view['blackboard_keys']),
            'gateways': len(view['gateways']),
            'data_edges': len(view['potential_service_data'])}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source', default='outputs/service_graph.json')
    p.add_argument('--tree', default='dialogue_demo/BehaviorTree.json')
    p.add_argument('--access', default='sg_pipeline/access_map.json')
    p.add_argument('--output', default='outputs/service_view.json')
    p.add_argument('--upload', action='store_true', help='Upload only after preview')
    a = p.parse_args()
    result = project(json.loads(Path(a.source).read_text(encoding='utf8')),
                     next(iter(json.loads(Path(a.tree).read_text(encoding='utf8'))['trees'])),
                     json.loads(Path(a.access).read_text(encoding='utf8')))
    out = Path(a.output); out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding='utf8')
    print(f"Generated: {out}; services={len(result['services'])}; BB keys={len(result['blackboard_keys'])}; "
          f"gateways={len(result['gateways'])}; potential dataflow={len(result['potential_service_data'])}")
    if a.upload:
        print('Uploaded:', upload(result))


if __name__ == '__main__':
    main()
